spring:
  application: {name: 'spring-boot-consul-example'}
  cloud:
    consul:
      enabled: 'true'
      host: http://localhost
      port: 8600
      discovery: {healthCheckInterval: 300s}
      config: {fail-fast: true}